### ISSUE TITLE
doesnt go beyond displaying captcha

### ISSUE THREAD

**Issue by test2a** [combustor/reddit-accounts-generator#1]
d
  browser.find_element_by_id('regPassword').click()
creator.py:37: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  browser.find_element_by_id('regPassword').send_keys("Super@1234")
creator.py:39: DeprecationWarning: find_element_by_css_selector is deprecated. Please use find_element(by=By.CSS_SELECTOR, value=css_selector) instead
  browser.find_element_by_css_selector('button.AnimatedForm__submitButton:nth-child(3)').click() #clicks signup to show captcha
[*] Solve captcha, create account, then press enter... enter 'r' as input if captcha doesn't appear to skip username

**Comment by test2a** [comment]
also, can we use proxies because i created one account and it gave me 8 minutes cooldown period.............

i am on linux btw

**Comment by combustor** [comment]
Yep, I'm working on it. 
I'm mostly done too and it'll be uploaded today.


Now the proxy thing is a whole different problem, I will try to solve it though.

**Comment by test2a** [comment]
@combustor i mean you can look at how placebot people are doing socks proxies and reuse that?
