### ISSUE TITLE
Force Close

### ISSUE THREAD

**Issue by 16DigitCC** [combustor/reddit-accounts-generator#3]
When i click creator.py is open cmd and auto close. When im using cmd and type py creator.py script error like this
![image](https://user-images.githubusercontent.com/25837207/161573644-0ee785fd-2f53-4047-a075-593cec028f16.png)

**Comment by combustor** [comment]
Yes, you need to type "pip install polling2" and "pip install selenium" in cmd and then run it

**Comment by 16DigitCC** [comment]
Thanks , Work
