### ISSUE TITLE
use geckodriver-autoinstaller?

### ISSUE THREAD

**Issue by test2a** [combustor/reddit-accounts-generator#6]
https://pypi.org/project/geckodriver-autoinstaller/

should i add this in the requirements.txt file so that its more easy to get started?

**Comment by combustor** [comment]
Please do, also delete the geckodriver that's already included

**Comment by test2a** [comment]
@combustor what geckodriver is given by default? werent we supposed to install it ourselves?

**Comment by combustor** [comment]
> @combustor what geckodriver is given by default? werent we supposed to install it ourselves?

there's one included in this repo, it barely updates (last update was in 2021) so I didn't really care but for futureproofing there should be an autoinstaller

**Comment by test2a** [comment]
@combustor oh yeah, got it. it was windows only so i didnt even know it was there
